### ISSUE TITLE
make opencv_catkin error

### ISSUE THREAD

**Issue by liweizju** [ethz-asl/maplab#172]
I'm trying to build this awesome work on Ubuntu 18.04, but I get stuck in the following error:

make[3]: warning: -jN forced in submake: disabling jobserver mode.
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from /usr/include/OpenEXR/ImfFrameBuffer.h:55,
                 from /usr/include/OpenEXR/ImfInputFile.h:47,
                 from /home/liwei/maplab_ws/build/opencv3_catkin/opencv3_src/modules/imgcodecs/src/grfmt_exr.hpp:53,
                 from /home/liwei/maplab_ws/build/opencv3_catkin/opencv3_src/modules/imgcodecs/src/grfmts.hpp:53,
                 from /home/liwei/maplab_ws/build/opencv3_catkin/opencv3_src/modules/imgcodecs/src/loadsave.cpp:47:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[5]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all] Error 2
make[2]: *** [opencv3_src-prefix/src/opencv3_src-stamp/opencv3_src-build] Error 2
make[1]: *** [CMakeFiles/opencv3_src.dir/all] Error 2
make: *** [all] Error 2

The VPN has been set and the downloading processes are OK. Just have no idea what's the problem here... 
catkin config is attached.
Any suggestions are appreciated, thanks~

![Screenshot from 2019-11-02 16-34-33](https://user-images.githubusercontent.com/10171493/68068350-b1b31e00-fd8e-11e9-9595-05233dd629ab.png)

**Comment by rjcortese** [comment]
I'm having similar issue maybe where the build fails on opencv3_catkin. However mine seems to fail because of a CMake Error:
